- src/Models/Apps.php
- src/Models/FileSystem.php
- src/Models/FilesystemSettings.php
- src/Providers/FileSystemProvider.php
- src/Traits/FileManagementTrait.php
- src/Traits/ModelSettingsTrait.php
- storage/db/migrations/20181219160754_add_anual_price.php
- storage/db/seeds/AppsSettingsSeeder.php
> Hotfix filesystem s3

- src/Core/config.php
- src/Models/EmailTemplates.php
- src/Providers/ViewProvider.php
- src/Template.php
- storage/view/.gitignore
add template parse function , to allow use to parse volt files from  string in the DB
> Feature  Email Template

- psalm.xml
- src/Cli/tasks/QueueTask.php
- src/Jobs/PendingDispatch.php
- Fix who is the job running for?
- add psalm to replace scrutinizer
> fix job user info and add psalm

- scrutinizer.yml
- src/Api/Controllers/UsersController.php
- src/Mapper/CompaniesGroupsMapper.php
- src/Mapper/UserMapper.php
- src/Middleware/AuthenticationMiddleware.php
- src/Middleware/NotFoundMiddleware.php
- src/Traits/UsersAssociatedTrait.php
- Use DTO on UserController
- Update Scrutinizer
> [WIP] fixes to the code while writting the documentation

- src/Api/Controllers/AppsController.php
- src/Api/Controllers/AppsPlansController.php
- src/Api/Controllers/CompaniesBranchesController.php
- src/Api/Controllers/UsersInviteController.php
- App switcher endpoint
- Cleaning up old exceptions
> Feature app switcher

- src/Middleware/TokenBase.php
- src/Models/Subscription.php
- src/Traits/SubscriptionPlanLimitTrait.php
- Fix issue with payment routes
> Hotfix subscription auth

- src/Api/Controllers/UsersInviteController.php
Same response for invite as signup
> have the same response for user invite as signup

- src/Api/Controllers/UserLinkedSourcesController.php
- If the user has a linked device delete, it wasn't been updated
> Update User Device

- src/Contracts/Mapper/RelationshipTrait.php
- src/Mapper/UserMapper.php
- Change the user dto visibilty needed when overwriting the function by a diff project
> change user dto visibility function

- src/Contracts/Controllers/ProcessOutputMapperTrait.php
- Fix the issue when calling a route with relationship + format , its ignoring the relationship
------
Example:
`{{API}}/v1/users?relationships=roles,files&format=true`
> Hotfix Dto with Relationship + Format

- src/Api/Controllers/AuthController.php
- src/Listener/User.php
- src/Mapper/UserMapper.php
- src/Models/Apps.php
- src/Models/Roles.php
- src/Models/Users.php
- src/Providers/ViewProvider.php
- src/Traits/PermissionsTrait.php
- Fix relationships with Roles to only work with the current company id
> [WIP] Hotfix User Roles

- src/Mapper/UserMapper.php
- If we dont get access list , return empty array for all permissions
> User AccesList

- src/Traits/FileSystemModelTrait.php
- Allow the app to determine if the images are public by accessing the entity or do you have to access the entity and be on the same corporation. This behavior is needed depending of the type of app you are building
> Allow app to determine accesability of images

- src/Filesystem/Helper.php
- src/Models/FileSystem.php
- src/Traits/FileManagementTrait.php
- Add height, width and orientation to the image
> Hotfix canvas images

- src/Filesystem/Helper.php
- storage/db/migrations/20181029002222_gewear_canvas_init.php
- storage/db/migrations/20181205053617_plans_subscriptions.php
- storage/db/migrations/schema.php
- Fix the name of the file we save to filesystem.
> Hotfix Filesystem filename

- src/Api/Controllers/NotificationsController.php
- Add filter by the current app
> Update Notifications Filter

- scrutinizer.yml
- src/Middleware/AnonymousMiddleware.php
- src/Middleware/AuthenticationMiddleware.php
- Add a missing class reference
- Change error for anonymous user in production
> Add missing Reference

- src/Http/Response.php
- We need to log every error in production
> Logs Errors on Production

- src/Listener/Company.php
- src/Listener/User.php
- Update default branch name to be company name
> Update Branch Name

- src/Api/Controllers/UsersController.php
- src/Dto/CustomFilter.php
- src/ErrorHandler.php
- src/EventsManager.php
- src/Filesystem/Helper.php
- src/Mapper/CompaniesGroupsMapper.php
- src/Mapper/CustomFieldsMapper.php
- src/Mapper/CustomFieldsModulesMapper.php
- src/Mapper/CustomFilterMapper.php
- src/Mapper/FileMapper.php
- src/Mapper/ListSchemaMapper.php
- src/Mapper/NotificationMapper.php
- src/Mapper/UserMapper.php
- src/Template.php
- src/Traits/FileManagementTrait.php
- src/Validation.php
- src/Webhooks.php
- Continue update formatting and spelling for update of SDk
> Update Formatting and Spelling

- src/Middleware/AuthenticationMiddleware.php
- src/Models/AppsKeys.php
> Update Auth Middelware

- src/Cli/tasks/ClearcacheTask.php
- src/Providers/ModelsCacheProvider.php
- src/Providers/RedisProvider.php
- Add Prefix to Redis cache to enable us to clean things up
- Pas params to redis DI so we can remove prefix and clean only this app keys
> Add Prefix to Redis Cache

- src/Traits/FileSystemModelTrait.php
- Allow user to get a file by the attributes we assign to them
*Note*: This is still slow as F, but the first draft will optimize and move to Redis on 0.2
> Add FileSystem getFileByNameWithAttributes

- src/Models/FileSystem.php
- Public Images on FileSystem Module
> Hotfix Public Images Modules

- src/Api/Controllers/AppsPlansController.php
- src/Traits/FileSystemModelTrait.php
> Add getFilesByName

- src/Api/Controllers/UsersController.php
Add location to createdfields and updatedFields
> Add location to updatable fields

- src/Api/Controllers/UsersController.php
add location in createdFields and updatedFields in usersControllers
> Allow add and update location

- src/Api/Controllers/UsersController.php
- Allow set user_active in a put request
> Allow update user_active

- src/Models/Users.php
Create method to validate if the current user below to current App.
> Create inApp validation to Users Model

- src/Api/Controllers/UsersController.php
- Allow update user_active attribute
> Allow update user_active attribute

- src/Filesystem/Helper.php
> Hotfix Uniquename 

- src/Filesystem/Helper.php
> Hotfix Unique Name

- src/Api/Controllers/SystemModulesController.php
- src/Traits/FileSystemModelTrait.php
- Phalcon4 change save and update behavior thank kamisama we have saveOrFail so, we updated it to work with filesystema
> Hotfix Filesystem

- src/Api/Controllers/SystemModulesController.php
- src/Models/FileSystemEntities.php
- src/Traits/FileSystemModelTrait.php
- Not limiting deleting images by filesystem
> Hotfix Filesystem Issues
